version: "3"

services:

  backend:
    image: ticket-service:0.0.1-snapshot
    ports:
      - "8080:8080"
    depends_on:
      - database
      - rabbitmq

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tickets
      POSTGRES_USER: maksim
      POSTGRES_PASSWORD: maksim

  additional-service:
    image: rmq-listener:1.0
    ports:
      - "8081:8081"
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "19999:15672"